### ISSUE TITLE
Including JupyterLab install steps

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ipympl-feedstock#26]
Would it make sense to include `jupyter labextension install` commands in build or link steps. 

Noticed in the [install instructions]( https://github.com/matplotlib/jupyter-matplotlib/#installation ) that some `jupyter labextension install` commands need to be run in conjunction with installing the `ipympl` package. Admittedly I don't know very much about what goes on under the hood in the extension install process, but would it be possible to integrate these steps into the Conda package installation? This would make it easier for users to install/uninstall and make it less likely that they forget a step.

Assuming this would be possible. There is a question of where to add these commands. If this is just adding/removing files (not modifying them), then adding `jupyter labextension install` should fit nicely in the build. If some existing files are modified, then adding the `jupyter labextension install`/`jupyter labextension uninstall` commands to the link steps might make more sense.

Any thoughts on this?

**Comment by blink1073** [comment]
The issue is that you might be running the kernel in a different environment than the frontend, so we expressly didn't bundle the lab extension tarball.

**Comment by jakirkham** [comment]
Maybe [split packages]( https://docs.conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html#outputs-section ) could be used to allow building both the client-side components and the server-side components to be distributed in appropriate packages?

**Comment by jasongrout** [comment]
Some thoughts:

For the cases where the user's kernel and server live in different environments, I don't think there's anything we can simplify. They'll have to install into both environments to serve the js from the server environment, and use the python code from the kernel environment.

However, probably the most common usecase is for the user to have the server and kernel in the same environment. If we optimize for this situation, then it may make sense to include the npm package with the python (either as a tarball in the same package, or as a dependency in a separate package). However, we'd see some bloat since there are at least two different bundles for two different frontends (classic notebook, JupyterLab). Do we include both javascript bundles? And if we decide to make the js into a separate package, it seems just a little odd to have an npm package we are already publishing be wrapped in a conda package that we'd also maintain.

**Comment by moorepants** [comment]
> And if we decide to make the js into a separate package, it seems just a little odd to have an npm package we are already publishing be wrapped in a conda package that we'd also maintain

Isn't this what all conda packages are. I think conda should be used to package the node oriented packages separately so that `conda install ipympl` just works.

**Comment by jakirkham** [comment]
How large is the js if bundled?

If we want to keep them separate, what about a split package?

From a purpose standpoint, it does make it a bit easier for Conda users as they can just use Conda to install the package (without needing to understand npm as well).

**Comment by martinRenou** [comment]
Now that JupyterLab 3 is a thing, the labextension is installed automatically with the conda package, this issue can be closed.
